version: '3.8'
services:
  mongo:
    image: mongo:6.0
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=dmarket
      - MONGO_INITDB_ROOT_USERNAME=dmarket
      - MONGO_INITDB_ROOT_PASSWORD=Xhdhy
      - MONGO_USERNAME=dmarket
      - MONGO_PASSWORD=Xhdhy
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - ./security/mongo-keyfile:/data/replicaset.key.devel
      - ./scripts/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    networks:
      - mongo-net
    entrypoint:
      - bash
      - -c
      - |
          cp /data/replicaset.key.devel /data/replica.key
          chmod 400 /data/replica.key
          chown 999:999 /data/replica.key
          exec docker-entrypoint.sh "$$@"
    command: mongod --bind_ip_all --replSet rs0 --keyFile /data/replica.key
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dmarket
      ME_CONFIG_MONGODB_ADMINPASSWORD: Xhdhy
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - mongo-net
    depends_on:
      - mongo

  mongo-init-replica:
    image: mongo:6.0
    networks:
      - mongo-net
    depends_on:
      - mongo
    command: 'bash -c "sleep 10 && mongo --host mongo --eval ''rs.initiate({_id: \"rs0\", members:[{_id: 0, host: \"mongo:27017\"}]})''"'
networks:
  mongo-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local